# noinspection PyUnresolvedReferences
from build_system.compiler.installed_instance.gcc import GCCCompilerInstance

# noinspection PyUnresolvedReferences
from build_system.compiler.installed_instance.msvc import MSVCCompilerInstance
