# noinspection PyUnresolvedReferences
from build_system.compiler.installed_instance.gnu import GNUCompilerInstance

# noinspection PyUnresolvedReferences
from build_system.compiler.installed_instance.msvc import MSVCCompilerInstance
